[package]
name = "tf-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
ndarray = "0.15.3"
random = "0.12.2"
tensorflow = {version="0.17.0", features = ["ndarray"]}